const jobs = [
    {
      id: 1,
      title: "Senior Software Engineer",
      salary: "$100 - $210 per hour",
      contractType: "Hourly contract",
      location: "Remote",
      workHours: "Weekly hours vary",
      companyName: "Mercor",
      companyWebsite: "mercor.com",
      description: "Mercor is recruiting U.S. and Europe-based Senior Software Engineers for research projects with leading AI labs. These projects involve debugging, refactoring, and writing test cases for complex codebases.",
      skills: ["Rust", "Go", "C++", "Java", "JavaScript", "Python"],
      responsibilities: [
        "Interface with AI researchers from top labs",
        "Work asynchronously on high-impact projects",
        "Write clean, maintainable code",
        "Participate in technical discussions and reviews",
      ],
      benefits: [
        "Competitive hourly rate",
        "Fully remote work",
        "Work with top AI researchers",
        "Flexible working hours (10-40 hours per week)",
      ],
      referralLink: "https://mercor.com/jobs/list_AAABk727v5IpZngzZr1P6Zgk",
      postedDaysAgo: 11,
    },
    {
      id: 2,
      title: "Full Stack Developer",
      salary: "$80 - $150 per hour",
      contractType: "Hourly contract",
      location: "Remote",
      workHours: "10 - 30 hours per week",
      companyName: "TechWorks",
      companyWebsite: "techworks.io",
      description: "TechWorks is looking for a Full Stack Developer to contribute to its cutting-edge web applications. You will work with modern frameworks, optimize performance, and enhance user experience.",
      skills: ["React", "Node.js", "GraphQL", "PostgreSQL", "TypeScript"],
      responsibilities: [
        "Develop and maintain scalable web applications",
        "Implement APIs and optimize database queries",
        "Ensure seamless user experience with responsive UI",
        "Participate in code reviews and technical discussions",
      ],
      benefits: [
        "Competitive hourly rate",
        "Opportunity to work with modern tech stack",
        "Flexible work schedule",
        "Collaborate with top engineers worldwide",
      ],
      referralLink: "https://techworks.io/jobs/fullstack-dev",
      postedDaysAgo: 5,
    },
    {
      id: 3,
      title: "Machine Learning Engineer",
      salary: "$120 - $250 per hour",
      contractType: "Hourly contract",
      location: "Hybrid (NYC & Remote)",
      workHours: "20 - 40 hours per week",
      companyName: "AI Innovators",
      companyWebsite: "aiinnovators.com",
      description: "AI Innovators is hiring Machine Learning Engineers to work on cutting-edge AI models. You will train, fine-tune, and deploy deep learning models for real-world applications.",
      skills: ["Python", "TensorFlow", "PyTorch", "NLP", "Computer Vision"],
      responsibilities: [
        "Develop and optimize deep learning models",
        "Work with large-scale datasets for training AI systems",
        "Deploy ML models into production environments",
        "Collaborate with researchers on new AI innovations",
      ],
      benefits: [
        "Top-tier hourly compensation",
        "Hybrid work environment",
        "Opportunity to contribute to world-class AI research",
        "Access to high-performance computing resources",
      ],
      referralLink: "https://aiinnovators.com/jobs/ml-engineer",
      postedDaysAgo: 3,
    },
    {
      id: 4,
      title: "DevOps Engineer",
      salary: "$90 - $180 per hour",
      contractType: "Hourly contract",
      location: "Remote",
      workHours: "15 - 35 hours per week",
      companyName: "CloudOps Solutions",
      companyWebsite: "cloudops.dev",
      description: "CloudOps Solutions is seeking a DevOps Engineer to automate and improve deployment pipelines. You will be responsible for cloud infrastructure, CI/CD, and security optimizations.",
      skills: ["AWS", "Docker", "Kubernetes", "Terraform", "Jenkins"],
      responsibilities: [
        "Manage cloud infrastructure and automate deployments",
        "Enhance system security and scalability",
        "Optimize CI/CD pipelines for efficiency",
        "Monitor and troubleshoot production environments",
      ],
      benefits: [
        "Work with cutting-edge cloud technologies",
        "Fully remote work flexibility",
        "Competitive pay and project-based bonuses",
        "Collaborate with a high-performance DevOps team",
      ],
      referralLink: "https://cloudops.dev/jobs/devops",
      postedDaysAgo: 8,
    },
    {
      id: 5,
      title: "Data Scientist",
      salary: "$110 - $220 per hour",
      contractType: "Hourly contract",
      location: "Remote",
      workHours: "20 - 40 hours per week",
      companyName: "BigData Analytics",
      companyWebsite: "bigdataanalytics.com",
      description: "BigData Analytics is looking for Data Scientists to analyze complex datasets, extract insights, and drive business decisions using machine learning and statistical models.",
      skills: ["Python", "SQL", "Pandas", "Scikit-Learn", "Data Visualization"],
      responsibilities: [
        "Analyze large datasets to uncover trends and patterns",
        "Develop machine learning models for business applications",
        "Create dashboards and data visualizations",
        "Collaborate with cross-functional teams on data-driven solutions",
      ],
      benefits: [
        "Competitive hourly pay",
        "Access to high-quality datasets",
        "Fully remote and flexible work schedule",
        "Opportunities for publishing research papers",
      ],
      referralLink: "https://bigdataanalytics.com/jobs/data-scientist",
      postedDaysAgo: 2,
    },
  ];

export default jobs;